POST http://localhost:3003/api/users
Content-Type: application/json

{
    "blogs": [],
    "username": "Mila",
    "name": "",
    "password": "eeeeee"
}
###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "name": "Donnie"
}

###
GET http://localhost:3003/api/users

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "refactoring code basics",
    "author": "Jack",
    "url": "url",
    "likes": 10
}

###
PUT http://localhost:3003/api/blogs/60a8d0a1a624ee6ca4dc40fc
Content-Type: application/json

{
    "title": "refactoring code",
    "author": "nora-lynn",
    "url": "url",
    "likes": 15

}

###
GET http://localhost:3003/api/blogs

###
DELETE http://localhost:3003/api/blogs/60a8d246c17d933c5058f946